# This nginx configuration emulates ingress API gateway for local development

server {
    listen 8080;

    # Accounts service
    location /accounts {
        proxy_pass http://accounts:8080;
    }

    # Loans service
    location /loans {
        proxy_pass http://loans:8080;
    }
    location /v0.1/loans {
        proxy_pass http://loans:8080;
    }
    location /v0.2/loans {
        proxy_pass http://loans:8080;
    }

    # Offers service
    location /offers{
        proxy_pass http://offers:8080;
    }
    location /v0.1/offers {
        proxy_pass http://offers:8080;
    }
    location /v0.2/offers {
        proxy_pass http://offers:8080;
    }
    location /v0.3/offers {
        proxy_pass http://offers:8080;
    }
    location /offers-count {
        proxy_pass http://offers:8080;
    }
    location /v0.1/offers-count {
        proxy_pass http://offers:8080;
    }
}
