export enum MetadataKey {
  ETHERS_CONTRACT = '@nftfi.api:ethers-contract',
  ETHERS_CONTRACT_BUILDER = `${ETHERS_CONTRACT}:builder`,
  ETHERS_CONTRACT_SUBSCRIBER = `${ETHERS_CONTRACT}:subscriber`,
  ETHERS_CONTRACT_EVENT_LISTENER = `${ETHERS_CONTRACT}:event-listener`,
  ETHERS_CONTRACT_EVENT_LISTENER_PARAMS = `${ETHERS_CONTRACT}:event-listener:params`,
  ETHERS_CONTRACT_EVENT_LISTENER_PARAM_ARGS = `${ETHERS_CONTRACT}:event-listener:params:args`,
  ETHERS_CONTRACT_EVENT_LISTENER_PARAM_LOG = `${ETHERS_CONTRACT}:event-listener:params:log`,
  ETHERS_CONTRACT_EVENT_LISTENER_PARAM_BLOCK = `${ETHERS_CONTRACT}:event-listener:params:block`,
  ETHERS_CONTRACT_EVENT_LISTENER_PARAM_INTERNALID = `${ETHERS_CONTRACT}:event-listener:params:internal-id`,
  ETHERS_CONTRACT_EVENT_LISTENER_PARAM_EMITTEDAT = `${ETHERS_CONTRACT}:event-listener:params:emitted-at`,
  ETHERS_CONTRACT_EVENT_LISTENER_PARAM_TXHASH = `${ETHERS_CONTRACT}:event-listener:params:txhash`,
  ETHERS_CONTRACT_EVENT_LISTENER_PARAM_CONTRACT = `${ETHERS_CONTRACT}:event-listener:params:contract`
}
