server {
    listen 8080;
    root /usr/share/nginx/html;
    rewrite ^/ns(.*)$ $1 last;

    location / {
      root   /usr/share/nginx/html;
      index  index.html index.htm;
      try_files $uri $uri/ /index.html;
    }

    location /health {
      return 200;
      access_log off;
    }

    port_in_redirect off;
    absolute_redirect off;

    include conf.d/proxy.locations;
}